### PR TITLE
Add db.collection.distinct() method

### LINKED ISSUE #38: distinct Implementation
Is there any way to use collection.distinct()?

### LINKED ISSUE #50: add db.collection.distinct() feature
hi, I'm creating a Mongoose like ODM built top of this library. I successfully added nearly all methods except for the `distinct` method can you please add that method. 

https://docs.mongodb.com/manual/reference/method/db.collection.distinct/

this issue is also mentioned in  [#38 ](https://github.com/manyuanrong/deno_mongo/issues/38) 
I fork this repo and tried to add that feature by myself but failed to do so that because I'm a beginner to rust.

I hope you add this feature.

and also version 0.8.0 doesn't seem to work on windows.

### PR DESCRIPTION
**Pull request by divy-work**
Implements [db.collection.distinct()](https://docs.rs/mongodb/1.0.0/mongodb/struct.Collection.html#method.distinct) method in deno_mongo.

Closes #38 
Closes #50

### CODE REVIEW

**Comment by divy-work** [comment]
@manyuanrong I've added almost everything except [`DistinctOptions`](https://docs.rs/mongodb/1.0.0/mongodb/options/struct.DistinctOptions.html). I think that part of rust-mongo is currently under development. 

Do you think we should add that?

**Comment by alirealasad** [comment]
any idea why the windows test are keep failing

**Comment by divy-work** [comment]
@alirealasad No idea, looks like a bug with virtual env or maybe the db connection is not closed.

**Comment by lucacasonato** [comment]
PR looks good 👍 

> No idea, looks like a bug with virtual env or maybe the db connection is not closed.

@divy-work Yeah, I think it is because the DB connection isn't closed. CI issue is tracked in #64. We should implement #57 and see if that helps.

**Comment by manyuanrong** [comment]
LGTM

**Pull request merged**
