### PR TITLE
Examples documentation

### PR DESCRIPTION
**Pull request by avalero**
I just wanted to check if you guys are ok with this kind documentation. If that's the case I will document all the functions. I am using it to teach at university.

### CODE REVIEW

**Comment by lucacasonato** [comment]
@avalero Documentation is always very welcome :-). I wonder if you could add the documentation inline on the functions using JS Doc. You can then get a pretty printed view of the JS Doc comments at https://doc.deno.land/https/deno.land/x/mongo@v0.12.1/mod.ts.

**Comment by avalero** [comment]
Yes!! will do it!

**Comment by lucacasonato** [comment]
Yup, looks good

**Comment by Lexpeartha** [comment]
Could we get examples for connecting with Atlas too?

**Pull request merged**
