### PR TITLE
Update for Deno 1.4.0

### PR DESCRIPTION
**Pull request by lucacasonato**
cc @manyuanrong 

~Waiting on https://github.com/manyuanrong/deno-plugin-prepare/pull/26~ Done

### CODE REVIEW

**Comment by linden** [comment]
@lucacasonato you'll need to configure a `ts-config.json` file in order to preserve "importsNotUsedAsValues". 
([https://deno.land/posts/v1.4#stricter-type-checks-in-code--unstablecode](https://deno.land/posts/v1.4#stricter-type-checks-in-code--unstablecode))

something like this would work
```
{
    "compilerOptions": {
        "importsNotUsedAsValues": "preserve"
    }
}
```

**Comment by lucacasonato** [comment]
@linden I know. I don’t want to do that though. We are going to make `importsNotUsedAsValues`
default and unchangeable in a month or two, so we want to migrate to the new default.

**Comment by manyuanrong** [comment]
@lucacasonato https://github.com/manyuanrong/deno-plugin-prepare/releases/tag/v0.7.5

**Comment by lucacasonato** [comment]
I'll do this in a minute @manyuanrong

**Comment by manyuanrong** [comment]
@lucacasonato The version in the source code is v0.11.2, but the release tag is v0.12.0

**Comment by lucacasonato** [comment]
> @lucacasonato The version in the source code is v0.11.2, but the release tag is v0.12.0

Right... :facepalm:

**Comment by lucacasonato** [comment]
@manyuanrong fixed in v0.12.1

**Pull request merged**
