### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pwhitdog**
Just adding a string there does not work. You must additionally import the bson address for the new ObjectId for the find command to work.

### CODE REVIEW

**Comment by manyuanrong** [comment]
Should export bson from deps.ts

**Comment by pwhitdog** [comment]
Can you show me what you mean because I currently cannot get the ObjectId class from your link "https://deno.land/x/mongo@v0.20.0/mod.ts" ? The only way I was able to get it was by using the link you had in desp.ts into my own file.

**Comment by manyuanrong** [comment]
Add a line to mod.ts:
```ts
export { Bson } from "./deps.ts"
```

**Comment by pwhitdog** [comment]
Sorry I did not know about your formatting of your typescript.

**Pull request merged**
